import {
  DoctorProfile,
  PatientProfile,
  DoctorAppointment,
  QueueEntry,
  ClinicalEncounter,
  DigitalPrescription,
  FollowUpRecord,
  LabOrder,
  DoctorAvailabilityConfig,
  DoctorNotificationItem,
  DoctorAnalyticsSummary,
} from "@/lib/types/doctor";

export const MOCK_DOCTOR_PROFILE: DoctorProfile = {
  id: "doc-tariq-01",
  userId: "user-doc-01",
  name: "Dr. Tariq Mahmood",
  title: "Consultant Cardiologist & Electrophysiologist",
  specialty: "Cardiologist",
  subSpecialty: "Interventional Cardiology & Hypertension",
  pmdcRegistration: "48291-P",
  pmdcVerified: true,
  qualifications: [
    "MBBS (Khyber Medical College)",
    "FCPS (Cardiology, CPSP)",
    "Fellowship in Interventional Cardiology (NICVD)",
    "MRCP (London, UK)",
  ],
  experienceYears: 16,
  languages: ["English", "Urdu", "Pashto", "Punjabi"],
  avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=400&auto=format&fit=crop",
  verificationStatus: "verified",
  bio: "Dr. Tariq Mahmood is an established consultant cardiologist in Peshawar and Islamabad with over 16 years of clinical excellence in cardiovascular therapeutics, ischemic heart disease, resistant hypertension, and heart failure management.",
  consultationFee: 2500,
  videoConsultationFee: 2000,
  rating: 4.9,
  reviewCount: 384,
  affiliatedClinics: [
    {
      id: "clinic-pesh-01",
      name: "City Medical Center",
      city: "Peshawar",
      address: "University Road, Near Khyber Teaching Hospital, Peshawar",
      tenantId: "tenant-pesh-cmc",
      roomNumber: "Consultation Suite 304",
      isPrimary: true,
      isActive: true,
      phone: "091-5843210",
    },
    {
      id: "clinic-isb-02",
      name: "Apex Heart & Specialty Institute",
      city: "Islamabad",
      address: "Sector F-8 Markaz, Islamabad",
      tenantId: "tenant-isb-apex",
      roomNumber: "Executive Clinic 12",
      isPrimary: false,
      isActive: true,
      phone: "051-2856430",
    },
  ],
  activeClinicId: "clinic-pesh-01",
};

export const MOCK_PATIENT_PROFILES: PatientProfile[] = [
  {
    id: "PAT-000123",
    patientUserId: "usr-pat-01",
    name: "Ahmed Khan",
    age: 34,
    gender: "male",
    phone: "0300-1234567",
    bloodGroup: "B+",
    allergies: ["Penicillin", "Sulfa drugs"],
    chronicConditions: ["Essential Hypertension (Stage 1)", "Mild Dyslipidemia"],
    currentMedications: ["Tab. Amlodipine 5mg OD", "Tab. Rosuvastatin 10mg HS"],
    emergencyContact: {
      name: "Zubair Khan",
      phone: "0333-9876543",
      relation: "Brother",
    },
    lastVisitDate: "18 Sep 2026",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    crossClinicRecordsAvailable: true,
    externalClinicName: "Apex Heart & Specialty Institute (Islamabad)",
  },
  {
    id: "PAT-000124",
    patientUserId: "usr-pat-02",
    name: "Fatima Bibi",
    age: 68,
    gender: "female",
    phone: "0301-7654321",
    bloodGroup: "O+",
    allergies: ["NSAIDs (Aspirin triggers bronchospasm)"],
    chronicConditions: ["Type 2 Diabetes Mellitus", "Hypertensive Cardiomyopathy", "Osteoarthritis"],
    currentMedications: [
      "Tab. Metformin 500mg BD",
      "Tab. Bisoprolol 2.5mg OD",
      "Tab. Losartan 50mg OD",
    ],
    emergencyContact: {
      name: "Muhammad Tariq",
      phone: "0312-5551234",
      relation: "Son",
    },
    lastVisitDate: "10 Sep 2026",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    crossClinicRecordsAvailable: false,
  },
  {
    id: "PAT-000125",
    patientUserId: "usr-pat-03", // Dependent under Ali Khan
    name: "Hamza Khan",
    age: 4,
    gender: "male",
    phone: "0300-4448888",
    guardianName: "Ali Khan",
    guardianRelation: "Father",
    bloodGroup: "A+",
    allergies: ["None known"],
    chronicConditions: ["Recurrent nocturnal cough under evaluation"],
    currentMedications: ["Syp. Levocetirizine 2.5ml HS"],
    emergencyContact: {
      name: "Ali Khan",
      phone: "0300-4448888",
      relation: "Father",
    },
    lastVisitDate: "05 Sep 2026",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    crossClinicRecordsAvailable: false,
  },
  {
    id: "PAT-000126",
    patientUserId: "usr-pat-04",
    name: "Ali Raza",
    age: 42,
    gender: "male",
    phone: "0321-9876540",
    bloodGroup: "AB+",
    allergies: ["Ciprofloxacin"],
    chronicConditions: ["Atypical Chest Pain", "GERD"],
    currentMedications: ["Cap. Esomeprazole 40mg OD AC"],
    emergencyContact: {
      name: "Samina Raza",
      phone: "0321-9876541",
      relation: "Wife",
    },
    lastVisitDate: "01 Sep 2026",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    crossClinicRecordsAvailable: true,
    externalClinicName: "Lady Reading Hospital (Peshawar)",
  },
  {
    id: "PAT-000127",
    patientUserId: "usr-pat-05",
    name: "Sara Noor",
    age: 28,
    gender: "female",
    phone: "0334-1122334",
    bloodGroup: "A-",
    allergies: ["No known drug allergies (NKDA)"],
    chronicConditions: ["Palpitations & Sinus Tachycardia on exertion"],
    currentMedications: ["Tab. Propranolol 10mg PRN"],
    emergencyContact: {
      name: "Noor Alam",
      phone: "0334-9988776",
      relation: "Father",
    },
    lastVisitDate: "15 Aug 2026",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    crossClinicRecordsAvailable: false,
  },
  {
    id: "PAT-000128",
    patientUserId: "usr-pat-06",
    name: "Zainab Bibi",
    age: 55,
    gender: "female",
    phone: "0345-6677889",
    bloodGroup: "B-",
    allergies: ["Iodinated Contrast"],
    chronicConditions: ["Uncontrolled Hypertension", "Chronic Kidney Disease (Stage 2)"],
    currentMedications: ["Tab. Valsartan 80mg OD", "Tab. Amlodipine 5mg OD"],
    emergencyContact: {
      name: "Kamran Shah",
      phone: "0345-1239874",
      relation: "Son",
    },
    lastVisitDate: "12 Sep 2026",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    crossClinicRecordsAvailable: false,
  },
  {
    id: "PAT-000129",
    patientUserId: "usr-pat-07",
    name: "Muhammad Usman",
    age: 47,
    gender: "male",
    phone: "0313-9090901",
    bloodGroup: "O-",
    allergies: ["None known"],
    chronicConditions: ["Post-PCI (Stented LAD 2024)", "Hypercholesterolemia"],
    currentMedications: ["Tab. Clopidogrel 75mg OD", "Tab. Atorvastatin 40mg HS", "Tab. Metoprolol 25mg BD"],
    emergencyContact: {
      name: "Farah Usman",
      phone: "0313-9090902",
      relation: "Wife",
    },
    lastVisitDate: "20 Aug 2026",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    crossClinicRecordsAvailable: false,
  },
];

export const MOCK_APPOINTMENTS: DoctorAppointment[] = [
  {
    id: "apt-01",
    bookingRef: "DM-9101",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000123",
    patientName: "Ahmed Khan",
    patientAge: 34,
    patientGender: "male",
    patientPhone: "0300-1234567",
    scheduledAt: "2026-09-24",
    timeSlot: "09:00 AM",
    consultationType: "in_clinic",
    status: "in_progress",
    tokenNumber: "A-19",
    paymentStatus: "paid",
    fee: 2500,
    reasonForVisit: "Routine BP check & review of 24hr Holter monitoring report",
  },
  {
    id: "apt-02",
    bookingRef: "DM-9102",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000124",
    patientName: "Fatima Bibi",
    patientAge: 68,
    patientGender: "female",
    patientPhone: "0301-7654321",
    scheduledAt: "2026-09-24",
    timeSlot: "09:30 AM",
    consultationType: "in_clinic",
    status: "waiting",
    tokenNumber: "A-20",
    paymentStatus: "paid",
    fee: 2500,
    reasonForVisit: "Mild bilateral ankle swelling and shortness of breath upon exertion",
  },
  {
    id: "apt-03",
    bookingRef: "DM-9103",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000125",
    patientName: "Hamza Khan (Child of Ali Khan)",
    patientAge: 4,
    patientGender: "male",
    patientPhone: "0300-4448888",
    scheduledAt: "2026-09-24",
    timeSlot: "10:00 AM",
    consultationType: "in_clinic",
    status: "waiting",
    tokenNumber: "A-21",
    paymentStatus: "pay_at_clinic",
    fee: 2500,
    reasonForVisit: "Cardiac murmur clearance requested by pediatrician",
  },
  {
    id: "apt-04",
    bookingRef: "DM-9104",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000126",
    patientName: "Ali Raza",
    patientAge: 42,
    patientGender: "male",
    patientPhone: "0321-9876540",
    scheduledAt: "2026-09-24",
    timeSlot: "10:30 AM",
    consultationType: "in_clinic",
    status: "waiting",
    tokenNumber: "A-22",
    paymentStatus: "paid",
    fee: 2500,
    reasonForVisit: "Recurrent retrosternal burning pain after meals and fast walking",
  },
  {
    id: "apt-05",
    bookingRef: "DM-9105",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000127",
    patientName: "Sara Noor",
    patientAge: 28,
    patientGender: "female",
    patientPhone: "0334-1122334",
    scheduledAt: "2026-09-24",
    timeSlot: "11:00 AM",
    consultationType: "video",
    status: "waiting",
    tokenNumber: "A-23",
    paymentStatus: "paid",
    fee: 2000,
    reasonForVisit: "Online Telehealth: Sudden episodes of racing heart rate (SVT suspicion)",
  },
  {
    id: "apt-06",
    bookingRef: "DM-9106",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000128",
    patientName: "Zainab Bibi",
    patientAge: 55,
    patientGender: "female",
    patientPhone: "0345-6677889",
    scheduledAt: "2026-09-24",
    timeSlot: "11:30 AM",
    consultationType: "in_clinic",
    status: "confirmed",
    tokenNumber: "A-24",
    paymentStatus: "pay_at_clinic",
    fee: 2500,
    reasonForVisit: "Follow-up for resistant hypertension titration",
  },
  {
    id: "apt-07",
    bookingRef: "DM-9107",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000129",
    patientName: "Muhammad Usman",
    patientAge: 47,
    patientGender: "male",
    patientPhone: "0313-9090901",
    scheduledAt: "2026-09-24",
    timeSlot: "12:00 PM",
    consultationType: "in_clinic",
    status: "scheduled",
    tokenNumber: "A-25",
    paymentStatus: "paid",
    fee: 2500,
    reasonForVisit: "Annual post-stent cardiac evaluation & stress echocardiography review",
  },
  // Morning completed appointments
  {
    id: "apt-08",
    bookingRef: "DM-9088",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000123",
    patientName: "Rashid Minhas",
    patientAge: 52,
    patientGender: "male",
    patientPhone: "0302-9988771",
    scheduledAt: "2026-09-24",
    timeSlot: "08:00 AM",
    consultationType: "in_clinic",
    status: "completed",
    tokenNumber: "A-15",
    paymentStatus: "paid",
    fee: 2500,
    reasonForVisit: "Early morning ECG & blood pressure adjustment",
  },
  {
    id: "apt-09",
    bookingRef: "DM-9089",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000124",
    patientName: "Kalsoom Akhtar",
    patientAge: 61,
    patientGender: "female",
    patientPhone: "0331-4455667",
    scheduledAt: "2026-09-24",
    timeSlot: "08:20 AM",
    consultationType: "in_clinic",
    status: "completed",
    tokenNumber: "A-16",
    paymentStatus: "paid",
    fee: 2500,
    reasonForVisit: "Diabetic vascular checkup and lipid test review",
  },
  {
    id: "apt-10",
    bookingRef: "DM-9090",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000126",
    patientName: "Gulzar Ahmad",
    patientAge: 39,
    patientGender: "male",
    patientPhone: "0315-1237894",
    scheduledAt: "2026-09-24",
    timeSlot: "08:40 AM",
    consultationType: "in_clinic",
    status: "completed",
    tokenNumber: "A-17",
    paymentStatus: "paid",
    fee: 2500,
    reasonForVisit: "Pre-employment cardiac fitness certification",
  },
  {
    id: "apt-11",
    bookingRef: "DM-9091",
    tenantId: "tenant-pesh-cmc",
    clinicId: "clinic-pesh-01",
    clinicName: "City Medical Center — Peshawar",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    patientProfileId: "PAT-000127",
    patientName: "Kamran Bangash",
    patientAge: 44,
    patientGender: "male",
    patientPhone: "0300-9871234",
    scheduledAt: "2026-09-24",
    timeSlot: "08:50 AM",
    consultationType: "in_clinic",
    status: "no_show",
    tokenNumber: "A-18",
    paymentStatus: "pay_at_clinic",
    fee: 2500,
    reasonForVisit: "Missed appointment, patient did not report to reception",
  },
];

export const MOCK_QUEUE: QueueEntry[] = [
  {
    id: "q-01",
    appointmentId: "apt-01",
    patientProfileId: "PAT-000123",
    patientName: "Ahmed Khan",
    age: 34,
    gender: "male",
    tokenNumber: "A-19",
    consultationType: "in_clinic",
    priority: "normal",
    waitingSinceMinutes: 0,
    status: "in_progress",
    estimatedWaitMinutes: 0,
    appointmentTime: "09:00 AM",
    reason: "General Consultation & 24hr Holter Review",
  },
  {
    id: "q-02",
    appointmentId: "apt-02",
    patientProfileId: "PAT-000124",
    patientName: "Fatima Bibi",
    age: 68,
    gender: "female",
    tokenNumber: "A-20",
    consultationType: "in_clinic",
    priority: "urgent",
    waitingSinceMinutes: 12,
    status: "waiting",
    estimatedWaitMinutes: 5,
    appointmentTime: "09:30 AM",
    reason: "Ankle swelling & SOB on mild exertion",
  },
  {
    id: "q-03",
    appointmentId: "apt-03",
    patientProfileId: "PAT-000125",
    patientName: "Hamza Khan (Child)",
    age: 4,
    gender: "male",
    tokenNumber: "A-21",
    consultationType: "in_clinic",
    priority: "normal",
    waitingSinceMinutes: 18,
    status: "waiting",
    estimatedWaitMinutes: 15,
    appointmentTime: "10:00 AM",
    reason: "Pediatric heart murmur evaluation",
  },
  {
    id: "q-04",
    appointmentId: "apt-04",
    patientProfileId: "PAT-000126",
    patientName: "Ali Raza",
    age: 42,
    gender: "male",
    tokenNumber: "A-22",
    consultationType: "in_clinic",
    priority: "normal",
    waitingSinceMinutes: 22,
    status: "waiting",
    estimatedWaitMinutes: 25,
    appointmentTime: "10:30 AM",
    reason: "Retrosternal chest tightness after walking",
  },
  {
    id: "q-05",
    appointmentId: "apt-05",
    patientProfileId: "PAT-000127",
    patientName: "Sara Noor",
    age: 28,
    gender: "female",
    tokenNumber: "A-23",
    consultationType: "video",
    priority: "normal",
    waitingSinceMinutes: 8,
    status: "waiting",
    estimatedWaitMinutes: 35,
    appointmentTime: "11:00 AM",
    reason: "Episodic palpitations (Telehealth)",
  },
];

export const MOCK_LAB_ORDERS: LabOrder[] = [
  {
    id: "lab-01",
    testName: "Lipid Profile Fasting",
    category: "Biochemistry",
    priority: "routine",
    status: "results_available",
    notes: "Evaluate response to Rosuvastatin 10mg",
    resultSummary: "Total Cholesterol: 218 mg/dL (High), LDL: 142 mg/dL (High), HDL: 44 mg/dL, Triglycerides: 160 mg/dL",
    referenceRange: "Total Chol < 200, LDL < 100, HDL > 40, Triglycerides < 150 mg/dL",
    abnormalFlag: true,
    orderedAt: "2026-09-20",
    completedAt: "2026-09-22",
  },
  {
    id: "lab-02",
    testName: "12-Lead Electrocardiogram (ECG)",
    category: "Cardiology Diagnostics",
    priority: "stat",
    status: "reviewed",
    notes: "Assess for left ventricular strain or acute ischemic ST-T changes",
    resultSummary: "Sinus rhythm at 72 bpm, normal axis. Mild voltage criteria for LVH, no acute STEMI.",
    referenceRange: "Normal sinus rhythm (60-100 bpm)",
    abnormalFlag: false,
    orderedAt: "2026-09-24",
    completedAt: "2026-09-24",
  },
  {
    id: "lab-03",
    testName: "Serum Electrolytes & Creatinine",
    category: "Nephrology / Biochemistry",
    priority: "urgent",
    status: "results_available",
    notes: "Monitoring renal function on ACEi / ARB therapy",
    resultSummary: "Serum Creatinine: 1.1 mg/dL, Blood Urea: 28 mg/dL, Potassium (K+): 4.6 mEq/L, Sodium (Na+): 139 mEq/L",
    referenceRange: "Creatinine: 0.7 - 1.2 mg/dL, Potassium: 3.5 - 5.0 mEq/L",
    abnormalFlag: false,
    orderedAt: "2026-09-21",
    completedAt: "2026-09-23",
  },
  {
    id: "lab-04",
    testName: "HbA1c (Glycated Hemoglobin)",
    category: "Endocrinology",
    priority: "routine",
    status: "ordered",
    notes: "3-month glycemic control assessment",
    resultSummary: "Sample collected at pathology desk, awaiting analyzer run.",
    abnormalFlag: false,
    orderedAt: "2026-09-24",
  },
  {
    id: "lab-05",
    testName: "High-Sensitivity Troponin I (hs-cTnI)",
    category: "Cardiac Biomarkers",
    priority: "stat",
    status: "reviewed",
    notes: "Exclude acute myocardial injury",
    resultSummary: "hs-cTnI: 4.2 pg/mL (Within normal limit)",
    referenceRange: "< 14.0 pg/mL for non-acute baseline",
    abnormalFlag: false,
    orderedAt: "2026-09-18",
    completedAt: "2026-09-18",
  },
];

export const MOCK_CONSULTATIONS: ClinicalEncounter[] = [
  {
    id: "enc-01",
    appointmentId: "apt-01",
    patientProfileId: "PAT-000123",
    patientName: "Ahmed Khan",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    clinicId: "clinic-pesh-01",
    tenantId: "tenant-pesh-cmc",
    date: "2026-09-24",
    chiefComplaint: "Follow-up for essential hypertension & review of Holter monitor.",
    symptoms: ["Occasional mild morning headache", "Fatigue after intense work"],
    vitals: {
      bpSystolic: 138,
      bpDiastolic: 86,
      heartRate: 74,
      temperature: 98.4,
      spo2: 98,
      weightKg: 78,
      heightCm: 175,
      bmi: 25.5,
    },
    clinicalNotes:
      "Patient is currently compliant with Amlodipine 5mg. Holter report demonstrates baseline sinus rhythm with average 72 bpm, rare isolated premature ventricular contractions (PVCs) < 0.2%, no sustained ventricular tachycardia. Blood pressure remains slightly above optimal goal (target < 130/80).",
    assessment: "Primary Hypertension (suboptimally controlled), Mild Dyslipidemia.",
    diagnosis: "Essential (primary) hypertension, Stage 1; Dyslipidemia",
    icd10Code: "I10 / E78.5",
    medications: [
      {
        id: "med-01",
        name: "Tab. Amlodipine",
        genericName: "Amlodipine Besylate",
        dosage: "5 mg",
        frequency: "OD (1-0-0) Once Daily",
        duration: "30 Days",
        instructions: "Take in morning after breakfast",
        route: "oral",
      },
      {
        id: "med-02",
        name: "Tab. Rosuvastatin",
        genericName: "Rosuvastatin Calcium",
        dosage: "10 mg",
        frequency: "OD (0-0-1) Once Daily at Night",
        duration: "30 Days",
        instructions: "Take at bedtime",
        route: "oral",
      },
      {
        id: "med-03",
        name: "Tab. Valsartan",
        genericName: "Valsartan",
        dosage: "80 mg",
        frequency: "OD (1-0-0) Once Daily",
        duration: "30 Days",
        instructions: "Combine with Amlodipine for synergistic BP control",
        route: "oral",
      },
    ],
    labOrders: [
      {
        id: "lab-sub-01",
        testName: "Serum Electrolytes & Creatinine",
        category: "Biochemistry",
        priority: "routine",
        status: "ordered",
        notes: "Check baseline K+ and eGFR 4 weeks post-Valsartan initiation",
        orderedAt: "2026-09-24",
      },
    ],
    followUpRequired: true,
    followUpDate: "2026-10-24",
    followUpReason: "Assess 4-week BP response and renal profile on dual antihypertensive therapy.",
    status: "in_progress",
  },
];

export const MOCK_PRESCRIPTIONS: DigitalPrescription[] = [
  {
    id: "rx-01",
    prescriptionNumber: "RX-2026-0918-01",
    consultationId: "enc-prev-01",
    appointmentId: "apt-prev-01",
    patientProfileId: "PAT-000123",
    patientName: "Ahmed Khan",
    patientAge: 34,
    patientGender: "male",
    patientPhone: "0300-1234567",
    doctorId: "doc-tariq-01",
    doctorName: "Dr. Tariq Mahmood",
    doctorSpecialty: "Consultant Cardiologist",
    pmdcRegistration: "48291-P",
    clinicName: "City Medical Center",
    clinicAddress: "University Road, Peshawar, Khyber Pakhtunkhwa",
    clinicPhone: "091-5843210",
    date: "18 Sep 2026",
    diagnosis: "Essential Hypertension; Dyslipidemia",
    vitalsSummary: "BP: 142/90 mmHg | HR: 76 bpm | SpO2: 98% | Wt: 78 kg",
    medicines: [
      {
        id: "rx-med-01",
        name: "Tab. Amlodipine 5mg",
        genericName: "Amlodipine Besylate",
        dosage: "1 Tablet",
        frequency: "OD (1-0-0) Morning",
        duration: "30 Days",
        instructions: "After breakfast",
        route: "oral",
      },
      {
        id: "rx-med-02",
        name: "Tab. Rosuvastatin 10mg",
        genericName: "Rosuvastatin Calcium",
        dosage: "1 Tablet",
        frequency: "OD (0-0-1) Night",
        duration: "30 Days",
        instructions: "At bedtime",
        route: "oral",
      },
    ],
    doctorNotes: "Low salt diet (< 5g/day), brisk walking 30 mins daily. Avoid NSAIDs without consultation.",
    followUpText: "Follow-up with home BP log in 1 week or earlier if BP > 160/100.",
    signatureText: "Electronically Signed by Dr. Tariq Mahmood (PMDC: 48291-P)",
    issuedAt: "2026-09-18T10:45:00Z",
  },
];

export const MOCK_FOLLOW_UPS: FollowUpRecord[] = [
  {
    id: "fup-01",
    patientProfileId: "PAT-000124",
    patientName: "Fatima Bibi",
    age: 68,
    gender: "female",
    phone: "0301-7654321",
    doctorId: "doc-tariq-01",
    clinicId: "clinic-pesh-01",
    previousVisitDate: "10 Sep 2026",
    followUpDate: "2026-09-24", // Today!
    reason: "Review bilateral ankle swelling response after diuretic adjustment",
    status: "pending",
    notes: "Patient is queued in waiting room under token A-20.",
  },
  {
    id: "fup-02",
    patientProfileId: "PAT-000128",
    patientName: "Zainab Bibi",
    age: 55,
    gender: "female",
    phone: "0345-6677889",
    doctorId: "doc-tariq-01",
    clinicId: "clinic-pesh-01",
    previousVisitDate: "12 Sep 2026",
    followUpDate: "2026-09-24", // Today!
    reason: "Resistant hypertension titration and serum potassium check",
    status: "pending",
  },
  {
    id: "fup-03",
    patientProfileId: "PAT-000126",
    patientName: "Ali Raza",
    age: 42,
    gender: "male",
    phone: "0321-9876540",
    doctorId: "doc-tariq-01",
    clinicId: "clinic-pesh-01",
    previousVisitDate: "01 Sep 2026",
    followUpDate: "2026-09-24", // Today!
    reason: "Review upper GI endoscopy & cardiac stress test results",
    status: "pending",
  },
  {
    id: "fup-04",
    patientProfileId: "PAT-000129",
    patientName: "Muhammad Usman",
    age: 47,
    gender: "male",
    phone: "0313-9090901",
    doctorId: "doc-tariq-01",
    clinicId: "clinic-pesh-01",
    previousVisitDate: "20 Aug 2026",
    followUpDate: "2026-09-24", // Today!
    reason: "Post-stent 1-month clinical check & antiplatelet compliance check",
    status: "pending",
  },
  {
    id: "fup-05",
    patientProfileId: "PAT-000127",
    patientName: "Sara Noor",
    age: 28,
    gender: "female",
    phone: "0334-1122334",
    doctorId: "doc-tariq-01",
    clinicId: "clinic-pesh-01",
    previousVisitDate: "15 Aug 2026",
    followUpDate: "2026-09-28", // Upcoming
    reason: "Check Holter findings and thyroid profile (TSH)",
    status: "pending",
  },
  {
    id: "fup-06",
    patientProfileId: "PAT-000123",
    patientName: "Ahmed Khan",
    age: 34,
    gender: "male",
    phone: "0300-1234567",
    doctorId: "doc-tariq-01",
    clinicId: "clinic-pesh-01",
    previousVisitDate: "18 Sep 2026",
    followUpDate: "2026-09-22", // Overdue
    reason: "BP check 4 days post medication adjustment",
    status: "overdue",
    notes: "Patient arrived today (24 Sep) instead for Holter review.",
  },
];

export const MOCK_NOTIFICATIONS: DoctorNotificationItem[] = [
  {
    id: "notif-01",
    type: "check_in",
    title: "Patient Checked In",
    message: "Patient Fatima Bibi (Token A-20) has checked in at reception desk.",
    timestamp: "12 mins ago",
    isRead: false,
    priority: "high",
    link: "/doctor/queue",
  },
  {
    id: "notif-02",
    type: "lab_result",
    title: "Lab Result Available",
    message: "Fasting Lipid Profile for Ahmed Khan (PAT-000123) is ready with high LDL flag.",
    timestamp: "28 mins ago",
    isRead: false,
    priority: "high",
    link: "/doctor/labs",
  },
  {
    id: "notif-03",
    type: "follow_up",
    title: "Follow-Up Due Today",
    message: "4 scheduled follow-up visits are due today at City Medical Center.",
    timestamp: "1 hour ago",
    isRead: false,
    priority: "normal",
    link: "/doctor/follow-ups",
  },
  {
    id: "notif-04",
    type: "reminder",
    title: "Video Consultation Approaching",
    message: "Telehealth appointment with Sara Noor scheduled at 11:00 AM.",
    timestamp: "1.5 hours ago",
    isRead: true,
    priority: "normal",
    link: "/doctor/appointments",
  },
  {
    id: "notif-05",
    type: "system",
    title: "Clinic Advisory",
    message: "In-house lab analyzer maintenance scheduled between 02:00 PM and 03:00 PM today.",
    timestamp: "3 hours ago",
    isRead: true,
    priority: "normal",
  },
];

export const MOCK_AVAILABILITY: DoctorAvailabilityConfig = {
  doctorId: "doc-tariq-01",
  clinicId: "clinic-pesh-01",
  workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  startTime: "09:00",
  endTime: "17:00",
  slotDurationMinutes: 20,
  bufferMinutes: 5,
  breakStartTime: "13:00",
  breakEndTime: "14:00",
  consultationModes: ["in_clinic", "video"],
  roomNumber: "Consultation Suite 304",
  maxPatientsPerDay: 28,
};

export const MOCK_ANALYTICS: DoctorAnalyticsSummary = {
  todayAppointments: 24,
  waitingCount: 6,
  completedCount: 14,
  upcomingCount: 10,
  followUpsDueCount: 4,
  noShowCount: 1,
  avgWaitMinutes: 18,
  avgConsultationMinutes: 14,
  followUpRatePercent: 82,
  appointmentUtilizationPercent: 88,
  weeklyTrend: [
    { day: "Sat", count: 20, completed: 19 },
    { day: "Mon", count: 26, completed: 25 },
    { day: "Tue", count: 22, completed: 21 },
    { day: "Wed", count: 28, completed: 26 },
    { day: "Thu (Today)", count: 24, completed: 14 },
    { day: "Fri", count: 18, completed: 0 },
  ],
  hourlyPeaks: [
    { hour: "09:00", count: 5 },
    { hour: "10:00", count: 6 },
    { hour: "11:00", count: 5 },
    { hour: "12:00", count: 4 },
    { hour: "14:00", count: 3 },
    { hour: "15:00", count: 4 },
    { hour: "16:00", count: 3 },
  ],
  statusDistribution: [
    { status: "completed", label: "Completed", count: 14, color: "#10b981" },
    { status: "waiting", label: "In Waiting Room", count: 6, color: "#f59e0b" },
    { status: "scheduled", label: "Upcoming Later", count: 3, color: "#0ea5e9" },
    { status: "no_show", label: "No Show", count: 1, color: "#ef4444" },
  ],
};
