export interface SpecializedDoctor {
  id: string;
  name: string;
  title: string;
  specialty: string;
  category: string;
  image: string;
  experience: string;
  rating: number;
  fee: string;
  availableTime: string;
  location: string;
}

export interface DetailedClinic {
  id: string;
  slug: string;
  name: string;
  type: string;
  departmentName: string;
  overview: string;
  rating: number;
  reviews: number;
  location: string;
  city: string;
  phone: string;
  hours: string;
  emergencyAvailable: boolean;
  facilities: string[];
  services: string[];
  image: string;
  topDoctor: SpecializedDoctor;
  specializedDoctors: SpecializedDoctor[];
}

export const ALL_CLINICS_DATA: DetailedClinic[] = [
  {
    id: "clinic-1",
    slug: "cardiology-center",
    name: "Apex Heart & Medical Center",
    type: "Cardiovascular & Specialty Care",
    departmentName: "Cardiology & Vascular Institute",
    overview:
      "Heart aur cardiovascular diseases ki comprehensive diagnosis, emergency coronary triage, aur modern non-invasive cardiovascular checkups.",
    rating: 5.0,
    reviews: 248,
    location: "450 Lexington Ave, Manhattan, New York, NY",
    city: "New York",
    phone: "+1 (212) 555-0144",
    hours: "Open 24/7 • Emergency Ready",
    emergencyAvailable: true,
    facilities: ["24/7 Cardiac ICU", "In-House Pharmacy", "Emergency Unit", "Echo & Ultrasound Labs"],
    services: [
      "12-Lead ECG & Stress Test",
      "3D Color Echocardiography",
      "Comprehensive Heart Checkup",
      "Holter 24hr Rhythm Monitoring",
      "Cardiac Rehabilitation & Diet Consultation",
      "Digital Coronary Angiography",
    ],
    image: "https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?q=80&w=800&auto=format&fit=crop",
    topDoctor: {
      id: "doc-1",
      name: "Dr. Esita Jabed",
      title: "Chief Interventional Cardiologist",
      specialty: "Cardiologist",
      category: "Cardiology",
      image: "/images/doctor-hd-1.jpg",
      experience: "12+ Years Exp.",
      rating: 5.0,
      fee: "$50",
      availableTime: "Today • 02:00 PM",
      location: "New York, NY",
    },
    specializedDoctors: [
      {
        id: "doc-1",
        name: "Dr. Esita Jabed",
        title: "Chief Cardiologist",
        specialty: "Interventional Cardiology",
        category: "Cardiology",
        image: "/images/doctor-hd-1.jpg",
        experience: "12+ Years Exp.",
        rating: 5.0,
        fee: "$50",
        availableTime: "Today • 02:00 PM",
        location: "New York, NY",
      },
      {
        id: "doc-4",
        name: "Dr. James Wilson",
        title: "Senior Vascular Specialist",
        specialty: "Cardiovascular Surgery",
        category: "Cardiology",
        image: "/images/doctor-hd-4.jpg",
        experience: "10+ Years Exp.",
        rating: 4.9,
        fee: "$60",
        availableTime: "Tomorrow • 01:15 PM",
        location: "New York, NY",
      },
      {
        id: "doc-6",
        name: "Dr. David Chen",
        title: "Pediatric Heart Specialist",
        specialty: "Cardiology, Pediatric Heart",
        category: "Cardiology",
        image: "/images/doctor-hd-6.jpg",
        experience: "16+ Years Exp.",
        rating: 5.0,
        fee: "$65",
        availableTime: "Today • 04:30 PM",
        location: "New York, NY",
      },
    ],
  },
  {
    id: "clinic-2",
    slug: "eye-care-center",
    name: "VisionCare & Advanced Eye Institute",
    type: "Ophthalmology & Laser Eye Surgery",
    departmentName: "Ophthalmology (Eye Care & Vision)",
    overview:
      "Aankhon (Eye) ki tamam diseases, cataract laser surgery, glaucoma management, aur digital vision correction ki mukammal advanced facility.",
    rating: 4.9,
    reviews: 182,
    location: "840 Broadway St, New York, NY",
    city: "New York",
    phone: "+1 (212) 555-0899",
    hours: "Mon - Sat: 08:30 AM - 08:00 PM",
    emergencyAvailable: false,
    facilities: ["Laser Refractive Suite", "Optical Dispensary", "OCT Retinal Imaging", "Eye Daycare Ward"],
    services: [
      "Comprehensive Digital Eye Exam",
      "Cataract Blade-Free Laser Surgery",
      "LASIK & PRK Vision Correction Consultation",
      "Glaucoma Screening & Pressure Test",
      "Pediatric Ophthalmology & Strabismus",
      "Retina Optical Coherence Tomography (OCT)",
    ],
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800&auto=format&fit=crop",
    topDoctor: {
      id: "doc-eye-1",
      name: "Dr. Sophia Vance",
      title: "Senior Eye Surgeon & Cornea Specialist",
      specialty: "Ophthalmologist (Eye Specialist)",
      category: "Ophthalmology",
      image: "/images/doctor-hd-5.jpg",
      experience: "14+ Years Exp.",
      rating: 5.0,
      fee: "$55",
      availableTime: "Today • 11:30 AM",
      location: "New York, NY",
    },
    specializedDoctors: [
      {
        id: "doc-eye-1",
        name: "Dr. Sophia Vance",
        title: "Senior Eye Surgeon",
        specialty: "Ophthalmologist (Eye Specialist)",
        category: "Ophthalmology",
        image: "/images/doctor-hd-5.jpg",
        experience: "14+ Years Exp.",
        rating: 5.0,
        fee: "$55",
        availableTime: "Today • 11:30 AM",
        location: "New York, NY",
      },
      {
        id: "doc-eye-2",
        name: "Dr. Michael Ross",
        title: "Retina & Macula Specialist",
        specialty: "Vitreoretinal Eye Surgery",
        category: "Ophthalmology",
        image: "/images/doctor-hd-2.jpg",
        experience: "11+ Years Exp.",
        rating: 4.8,
        fee: "$60",
        availableTime: "Tomorrow • 03:00 PM",
        location: "New York, NY",
      },
    ],
  },
  {
    id: "clinic-3",
    slug: "pediatrics-center",
    name: "Metro Wellness & Pediatric Pavilion",
    type: "Pediatric & Family Healthcare",
    departmentName: "Pediatrics & Child Health",
    overview:
      "Navjaat bachon (newborns), infants, aur bacheon ki tamam bemariyon, routine vaccinations, aur adolescent growth care ka specialized center.",
    rating: 4.9,
    reviews: 194,
    location: "720 Wilshire Blvd, Los Angeles, CA",
    city: "Los Angeles",
    phone: "+1 (310) 555-0182",
    hours: "Mon - Sat: 08:00 AM - 10:00 PM",
    emergencyAvailable: true,
    facilities: ["Child Vaccination Booth", "Pediatric Play Lounge", "Dedicated Pharmacy", "Growth Lab"],
    services: [
      "Newborn & Infant Routine Checkup",
      "WHO Child Immunization & Vaccines",
      "Child Nutrition & Growth Monitoring",
      "Pediatric Asthma & Allergy Care",
      "Developmental Milestone Screening",
      "Childhood Fever & Infection Treatment",
    ],
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800&auto=format&fit=crop",
    topDoctor: {
      id: "doc-2",
      name: "Dr. Marcus Vance",
      title: "Lead Pediatric Consultant",
      specialty: "Pediatrician",
      category: "Pediatrics",
      image: "/images/doctor-hd-2.jpg",
      experience: "9+ Years Exp.",
      rating: 5.0,
      fee: "$45",
      availableTime: "Today • 03:30 PM",
      location: "Los Angeles, CA",
    },
    specializedDoctors: [
      {
        id: "doc-2",
        name: "Dr. Marcus Vance",
        title: "Head of Pediatrics",
        specialty: "General Pediatrics",
        category: "Pediatrics",
        image: "/images/doctor-hd-2.jpg",
        experience: "9+ Years Exp.",
        rating: 5.0,
        fee: "$45",
        availableTime: "Today • 03:30 PM",
        location: "Los Angeles, CA",
      },
      {
        id: "doc-3",
        name: "Dr. Tariq Ahmad",
        title: "Pediatric Critical Care Specialist",
        specialty: "Child Emergency Care",
        category: "Pediatrics",
        image: "/images/doctor-hd-3.jpg",
        experience: "14+ Years Exp.",
        rating: 5.0,
        fee: "$55",
        availableTime: "Tomorrow • 10:00 AM",
        location: "Los Angeles, CA",
      },
      {
        id: "doc-5",
        name: "Dr. Elena Rostova",
        title: "Pediatric Pulmonology Consultant",
        specialty: "Child Respiratory Health",
        category: "Pediatrics",
        image: "/images/doctor-hd-5.jpg",
        experience: "8+ Years Exp.",
        rating: 4.9,
        fee: "$40",
        availableTime: "Today • 05:00 PM",
        location: "Los Angeles, CA",
      },
    ],
  },
  {
    id: "clinic-4",
    slug: "neurology-hospital",
    name: "Mercy Diagnostic & Surgical Hospital",
    type: "Multi-Specialty & Surgical Suite",
    departmentName: "Neurology, Trauma & Multi-Specialty",
    overview:
      "Dimagh (Brain), spine, aur general surgical emergencies ki 24/7 advanced multi-specialty care unit with modern MRI aur CT scanners.",
    rating: 5.0,
    reviews: 312,
    location: "110 Michigan Ave, Chicago, IL",
    city: "Chicago",
    phone: "+1 (312) 555-0199",
    hours: "Open 24/7 • Emergency Ready",
    emergencyAvailable: true,
    facilities: ["3T MRI & 128-Slice CT", "24/7 Trauma Surgery Unit", "Central Pharmacy", "ICU & Stroke Center"],
    services: [
      "Advanced Brain MRI & Spine Imaging",
      "Stroke Immediate Intervention Unit",
      "Neurological EMG & Nerve Conduction Study",
      "Minimally Invasive Laparoscopic Surgery",
      "Emergency Trauma Stabilization",
      "24/7 Pathology & Blood Bank",
    ],
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=800&auto=format&fit=crop",
    topDoctor: {
      id: "doc-3",
      name: "Dr. Tariq Ahmad",
      title: "Chief of Emergency & Critical Care",
      specialty: "Critical Care & Trauma",
      category: "Neurology",
      image: "/images/doctor-hd-3.jpg",
      experience: "14+ Years Exp.",
      rating: 5.0,
      fee: "$55",
      availableTime: "Today • 01:00 PM",
      location: "Chicago, IL",
    },
    specializedDoctors: [
      {
        id: "doc-3",
        name: "Dr. Tariq Ahmad",
        title: "Critical Care Chief",
        specialty: "Trauma & Critical Care",
        category: "Neurology",
        image: "/images/doctor-hd-3.jpg",
        experience: "14+ Years Exp.",
        rating: 5.0,
        fee: "$55",
        availableTime: "Today • 01:00 PM",
        location: "Chicago, IL",
      },
      {
        id: "doc-6",
        name: "Dr. David Chen",
        title: "Senior General & Laparoscopic Surgeon",
        specialty: "General Surgery",
        category: "Surgery",
        image: "/images/doctor-hd-6.jpg",
        experience: "16+ Years Exp.",
        rating: 5.0,
        fee: "$65",
        availableTime: "Today • 04:30 PM",
        location: "Chicago, IL",
      },
    ],
  },
  {
    id: "clinic-5",
    slug: "orthopedics-center",
    name: "Summit Orthopedic & Spine Pavilion",
    type: "Orthopedics & Joint Rehabilitation",
    departmentName: "Orthopedics & Physical Therapy",
    overview:
      "Hadiyon (Bones), joron (Joints), knee replacement, aur sports injuries ki comprehensive orthopedic aur rehabilitation surgery.",
    rating: 4.8,
    reviews: 167,
    location: "3100 Oak Lawn Ave, Dallas, TX",
    city: "Dallas",
    phone: "+1 (214) 555-0320",
    hours: "Mon - Sat: 08:00 AM - 07:00 PM",
    emergencyAvailable: false,
    facilities: ["Digital X-Ray Suite", "Physical Therapy Gym", "Orthotic Lab", "Outpatient Surgery"],
    services: [
      "Total Knee & Hip Joint Replacement",
      "Arthroscopic Sports Injury Surgery",
      "Spine Decompression Therapy",
      "Digital Musculoskeletal Ultrasound",
      "Fracture Care & Cast Immobilization",
      "Post-Surgery Physical Rehabilitation",
    ],
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800&auto=format&fit=crop",
    topDoctor: {
      id: "doc-4",
      name: "Dr. James Wilson",
      title: "Director of Orthopedic Surgery",
      specialty: "Orthopedic & Joint Surgeon",
      category: "Orthopedics",
      image: "/images/doctor-hd-4.jpg",
      experience: "10+ Years Exp.",
      rating: 5.0,
      fee: "$60",
      availableTime: "Tomorrow • 09:30 AM",
      location: "Dallas, TX",
    },
    specializedDoctors: [
      {
        id: "doc-4",
        name: "Dr. James Wilson",
        title: "Orthopedic Surgeon",
        specialty: "Joint & Spine Surgery",
        category: "Orthopedics",
        image: "/images/doctor-hd-4.jpg",
        experience: "10+ Years Exp.",
        rating: 5.0,
        fee: "$60",
        availableTime: "Tomorrow • 09:30 AM",
        location: "Dallas, TX",
      },
    ],
  },
];
