"use client";

import React, { useState, useMemo } from "react";
import {
  Pill,
  Calendar,
  Stethoscope,
  Building2,
  Clock,
  Printer,
  Download,
  Info,
  Search,
  User,
  Plus,
} from "lucide-react";
import { FamilyMemberRecord, PatientUser } from "@/lib/types/patient";

interface PrescriptionsSectionProps {
  patientUser: PatientUser | null;
  familyMembers: FamilyMemberRecord[];
  onOpenBooking: () => void;
}

export default function PrescriptionsSection({
  patientUser,
  familyMembers,
  onOpenBooking,
}: PrescriptionsSectionProps) {
  const primaryName = patientUser?.name || "Muhammad Ahmed";
  const [selectedProfile, setSelectedProfile] = useState("all");

  const profileOptions = useMemo(() => {
    return [
      { id: "all", name: "All Family Prescriptions" },
      { id: primaryName.toLowerCase(), name: `${primaryName} (Self)` },
      ...familyMembers.map((m) => ({
        id: m.name.toLowerCase(),
        name: `${m.name} (${m.relation})`,
      })),
    ];
  }, [primaryName, familyMembers]);

  // Clean empty state ready for Doctor module prescription generation
  const prescriptions: any[] = [];

  return (
    <div className="space-y-6 animate-fadeInUp">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-slate-200 dark:border-slate-800 gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 px-3 py-0.5 rounded-full bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 text-xs font-bold mb-1">
            <Pill className="w-3.5 h-3.5" />
            <span>Digital E-Pharmacy</span>
          </div>
          <h1 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">
            Prescriptions
          </h1>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Verified physician digital prescriptions, medication dosage, and refill instructions.
          </p>
        </div>

        <button
          onClick={onOpenBooking}
          className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-2xl bg-teal-600 hover:bg-teal-500 text-white font-bold text-xs shadow-md shadow-teal-500/20 transition-all cursor-pointer self-start sm:self-auto"
        >
          <Plus className="w-4 h-4" />
          <span>Consult Doctor</span>
        </button>
      </div>

      {/* Filter Bar */}
      <div className="p-4 rounded-3xl bg-white dark:bg-[#0c1424] border border-slate-200/80 dark:border-slate-800 shadow-xs flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-xs font-semibold text-slate-500 dark:text-slate-400">
            Profile:
          </span>
          <select
            value={selectedProfile}
            onChange={(e) => setSelectedProfile(e.target.value)}
            className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white"
          >
            {profileOptions.map((opt) => (
              <option key={opt.id} value={opt.id}>
                {opt.name}
              </option>
            ))}
          </select>
        </div>

        <span className="text-xs text-slate-400 font-mono">0 active e-prescriptions</span>
      </div>

      {/* Empty State */}
      {prescriptions.length === 0 && (
        <div className="p-12 text-center rounded-3xl bg-white dark:bg-[#0c1424] border border-slate-200/80 dark:border-slate-800 shadow-xs">
          <div className="w-14 h-14 rounded-2xl bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 flex items-center justify-center mx-auto mb-3 shadow-xs">
            <Pill className="w-7 h-7" />
          </div>
          <h3 className="text-base font-bold text-slate-900 dark:text-white">
            No active prescriptions found
          </h3>
          <p className="mt-1 text-xs text-slate-500 dark:text-slate-400 max-w-md mx-auto leading-relaxed">
            When doctors prescribe medications during your consultations, digital e-prescriptions with dosage schedules and pharmacy fulfillment options will appear here.
          </p>

          <div className="mt-6 inline-flex items-center gap-2 p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 text-[11px] text-slate-600 dark:text-slate-300 text-left max-w-md">
            <Info className="w-4 h-4 text-emerald-500 flex-shrink-0" />
            <span>
              <strong>Integrated Clinic Pharmacy:</strong> Prescriptions generated by attending physicians are directly connected to our in-house clinic pharmacy network.
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
