import { DoctorPlanDefinition, PlanComparisonFeature } from "./types";

export const DOCTOR_PLANS: Record<"FREE" | "PRO" | "PREMIUM", DoctorPlanDefinition> = {
  FREE: {
    id: "FREE",
    name: "Free Plan",
    tagline: "Essential starter practice for independent solo physicians",
    priceMonthly: 0,
    priceAnnual: 0,
    currency: "PKR",
    bookingLimit: 50,
    maxDoctors: 1,
    maxLocations: 1,
    features: [
      "50 Online patient bookings per billing month",
      "1 Doctor & 1 Practice Location",
      "Standard Doctor Workspace & Calendar",
      "Digital Prescriptions & EMR access",
      "Lifetime access to existing medical records",
      "Standard Community Support",
    ],
  },
  PRO: {
    id: "PRO",
    name: "Pro Plan",
    tagline: "High-volume clinical workflow with unlimited patient appointments",
    priceMonthly: 2999,
    priceAnnual: 29990,
    currency: "PKR",
    bookingLimit: null, // Unlimited
    maxDoctors: 1,
    maxLocations: 2,
    recommended: true,
    features: [
      "Unlimited Online patient bookings",
      "Priority Public Directory Placement",
      "Custom Working Hours & Availability Buffer",
      "Full Clinical Revenue & Appointment Analytics",
      "Direct Patient WhatsApp & SMS Reminders",
      "Priority Clinical Support (4-hour SLA)",
    ],
  },
  PREMIUM: {
    id: "PREMIUM",
    name: "Premium Plan",
    tagline: "Comprehensive executive suite for multi-clinic consultants",
    priceMonthly: 6999,
    priceAnnual: 69990,
    currency: "PKR",
    bookingLimit: null, // Unlimited
    maxDoctors: 1,
    maxLocations: 5,
    features: [
      "Unlimited Online patient bookings",
      "Multi-Clinic & Hospital Affiliation Support",
      "Advanced Investigation & Lab Order Automation",
      "Clinical Document & Prescription Custom Branding",
      "Dedicated Medical Practice Account Manager",
      "24/7 Priority Emergency Support & Backup",
    ],
  },
};

export const PLAN_COMPARISON_MATRIX: PlanComparisonFeature[] = [
  {
    category: "Bookings & Practice",
    name: "Monthly Online Public Bookings",
    free: "50 bookings / mo",
    pro: "Unlimited",
    premium: "Unlimited",
  },
  {
    category: "Bookings & Practice",
    name: "Practice Locations Affiliated",
    free: "1 Clinic",
    pro: "Up to 2 Clinics",
    premium: "Up to 5 Clinics",
  },
  {
    category: "Bookings & Practice",
    name: "Public Directory Placement",
    free: "Standard",
    pro: "Boosted / Priority",
    premium: "Top Featured",
  },
  {
    category: "Clinical Workflow",
    name: "Digital Prescriptions & EMR",
    free: true,
    pro: true,
    premium: true,
  },
  {
    category: "Clinical Workflow",
    name: "Historical Data Retention",
    free: "Permanent (Never Locked)",
    pro: "Permanent (Never Locked)",
    premium: "Permanent (Never Locked)",
  },
  {
    category: "Clinical Workflow",
    name: "Reception & Walk-in Appointments",
    free: "Unlimited (No Quota Loss)",
    pro: "Unlimited (No Quota Loss)",
    premium: "Unlimited (No Quota Loss)",
  },
  {
    category: "Clinical Workflow",
    name: "Revenue & Clinical Analytics",
    free: "Basic 7-day",
    pro: "Full Multi-month",
    premium: "Custom Reports & Exports",
  },
  {
    category: "Support & Compliance",
    name: "PMDC Compliance Verification",
    free: true,
    pro: true,
    premium: true,
  },
  {
    category: "Support & Compliance",
    name: "WhatsApp / SMS Patient Reminders",
    free: false,
    pro: true,
    premium: true,
  },
  {
    category: "Support & Compliance",
    name: "Support SLA",
    free: "Standard Email (48h)",
    pro: "Priority Clinical (4h)",
    premium: "Dedicated Account Manager (24/7)",
  },
];
